### ISSUE TITLE
Low accuracy after data normalization

### ISSUE THREAD

**Issue by liruiwen** [soochan-lee/CN-DPM#7]
The original code works well on cifar100, however after I add normalization to cifar100 it gets very low accuracy. Is there any way to make it work on normalized dataset?

**Comment by soochan-lee** [comment]
You would need a different set of hyperparameters.
How many experts are created after normalization? Try changing  `log_alpha` (how easily an expert is created) and `classifier_chill` (controlling the loss ratio between VAE and classifier, see also #6).
